# World settings
chunk-size: 8
render-distance: 3

# General
reach: 6

# Colour of the block when hovered, where the list is RGBA ordered
hover-colour: [3, 23, 252, 100]

# Debug settings

# ? Visualise chunk borders
chunk-colours: False

# ? Visualise the derendered blocks around the player
colour-derendered: False

# ? Visualise the interactive blocks around player
bounding-box: False