# World settings
chunk-size: 8
render-distance: 3
seed: 1337

# Noise settings
amplitude: 5
frequency: 24
octaves: 2

# General
reach: 6

# Colour of the block when hovered, where the list is RGBA ordered
hover-colour: [3, 23, 252, 100]

# Debug settings

# ? Visualise chunk borders
chunk-colours: True

# ? Visualise the derendered blocks around the player
colour-derendered: False

# ? Visualise the interactive blocks around player
bounding-box: False