# World settings
chunk-size: 8
pregen-size: 2

# General
reach: 6

# Debug settings

# ? Visualise chunk borders
chunk-colours: False

# ? Visualise the derendered blocks around the player
colour-derendered: False

# ? Visualise the interactive blocks around player
bounding-box: False